# Generated by Django 5.2.7 on 2025-11-26 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar_evento', models.CharField(max_length=500, verbose_name='Lugar y dirección de evento')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('hora_inicio', models.IntegerField(choices=[(0, '00:00'), (1, '01:00'), (2, '02:00'), (3, '03:00'), (4, '04:00'), (5, '05:00'), (6, '06:00'), (7, '07:00'), (8, '08:00'), (9, '09:00'), (10, '10:00'), (11, '11:00'), (12, '12:00'), (13, '13:00'), (14, '14:00'), (15, '15:00'), (16, '16:00'), (17, '17:00'), (18, '18:00'), (19, '19:00'), (20, '20:00'), (21, '21:00'), (22, '22:00'), (23, '23:00')], verbose_name='Hora de inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de finalización')),
                ('hora_fin', models.IntegerField(choices=[(0, '00:00'), (1, '01:00'), (2, '02:00'), (3, '03:00'), (4, '04:00'), (5, '05:00'), (6, '06:00'), (7, '07:00'), (8, '08:00'), (9, '09:00'), (10, '10:00'), (11, '11:00'), (12, '12:00'), (13, '13:00'), (14, '14:00'), (15, '15:00'), (16, '16:00'), (17, '17:00'), (18, '18:00'), (19, '19:00'), (20, '20:00'), (21, '21:00'), (22, '22:00'), (23, '23:00')], verbose_name='Hora de finalización')),
                ('horas_trabajadas', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5, verbose_name='Horas trabajadas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Informe de jornada',
                'verbose_name_plural': 'Informes de jornada',
                'ordering': ['-fecha_inicio', '-hora_inicio'],
            },
        ),
    ]
